# test.rest

# Test API Login
#    This POST request sends the user's credentials.
#    If successful, it should return a 200 OK with a JSON response: { "message": "Login successful" }
POST http://127.0.0.1:8000/accounts/api/login/
Content-Type: application/json

{
  "username": "llui-guest-1",
  "password": "Magdalena0815"
}

###
# Test API Register
#    This POST request sends the user's data.
#    If successful, it should return a 200 OK with a JSON response
POST http://127.0.0.1:8000/accounts/api/register/
Content-Type: application/json

{
  "username": "llui-guest-1",
  "email": "llui@example.com",
  "password": "Magdalena0815",
  "password_confirm": "Magdalena0815"
}

###
#  Test Api logout
#    This delete the token
POST http://127.0.0.1:8000/accounts/api/logout/
Authorization: Token e2f91e852812403a0440b118a63423660e4d95be

###
#  Test Protected Endpoint
#    This GET request is protected. After a successful login, the session cookie is automatically stored (if rest-client.storeCookies is true).
#    It should return a 200 OK with some protected data: { "username": ...,  "info": ... }
GET http://127.0.0.1:8000/accounts/api/protected/
Authorization: Token e2f91e852812403a0440b118a63423660e4d95be

###
#  Test Protected and Group based Endpoint
#    This GET request is protected and group based

GET http://127.0.0.1:8000/accounts/api/doctor/
Authorization: Token e2f91e852812403a0440b118a63423660e4d95be